### ISSUE TITLE
Decouple Git specific code from the general model

### ISSUE THREAD

**Issue by marianopeck** [vasmalltalk/tonel-vast#10]
Right now we only have a small piece of code that looks for the hash and timestamp of the git commit to use it as default... that is nice. But in the future we would need to move this to a strategy that we can pass into the loader or something similar...because we don't want to couple FORMAT with git or tooling..

**Comment by eMaringolo** [comment]
Fixed in 56ffb412a4570c2797a7633e4759c9ba9b258af6
