### ISSUE TITLE
Add an extension to Pharo2VA to extract the list of packages in the load order

### ISSUE THREAD

**Issue by marianopeck** [vasmalltalk/tonel-vast#14]
This was discussed [here](https://github.com/vasmalltalk/tonel-vast/issues/11#issuecomment-529567386).
This would help bringing more complex projects as well as projects you didn't write and hence, you don't know the dependencies and order of load. 

We could include this as a feature in the [Pharo2VA](https://github.com/vasmalltalk/pharo2va) project.

**Comment by eMaringolo** [comment]
This won't be necessary since the loader will look recursively load packages from the repository if needed.
