### ISSUE TITLE
Honor order of SharedPool keys when writing initialization method

### ISSUE THREAD

**Issue by eMaringolo** [vasmalltalk/tonel-vast#21]
When writing a pool dictionary the order of the keys is not the same as the order in which the declaration method might have defined it.

**Comment by dalehenrich** [comment]
If I'm not mistaken I think that only the order of instance variables and class instance variables have semantics associated with them ...  preserving the order of class variables and pool names may not be practical in all implementations so I believe that it makes sense to sort them in alphabetical order (like we do with method selectors) ...
