### ISSUE TITLE
Implement headless importer

### ISSUE THREAD

**Issue by marianopeck** [vasmalltalk/tonel-vast#25]
Right now, what complicates me the most to use the Tonel reader is the popups and user needs. I propose to be able to plug a headless behavior that does:

1) Allow specifying a version (same) to be used when versioning all apps, classes, etc. If it is a git directory then assume the git hash etc (exactly as what the popup offers right now).
2) For base version, just assume the imported version is a root (no parent). Makes sense? 
3) Assume the prereqs are fine (don't popup to add/remove)
4) add an explicit boolean to control whether to version or not (rather than using nil as version to define we want open editions). 

Of course, it would be nice if all these things could be controlled/specified/set based on each user needs.

**Comment by eMaringolo** [comment]
This is what was presented as a "strategy based" behavior to avoid prompting for versions name, base editions, prerequisites, etc.

**Comment by dalehenrich** [comment]
I know that this about the Tonel reader, but it is an area where preferences decisions could be specified in the Rowan component file (i.e., for GemStone one can specify on a per package basis, the symbol dictionary where classes will be created). Just a thought.

**Comment by eMaringolo** [comment]
Today I'm working on it, the reason for this is that the ENVY Manager tools are very UI-bound, so what I'm creating is a set of strategies that you can use, by default you have the "interactive" strategy (it is, falls back to the UI prompters, etc.), and the others are to load the latest edition (e.g. as a Base edition), use the computed prerequisites, etc.

**Comment by dalehenrich** [comment]
I understand ... but once decisions have been made it would be convenient to record them on disk (in a component?) ... with that said, being able to choose to interactively drive the decisions is also important ...

**Comment by eMaringolo** [comment]
There is an initial support for this in 56ffb412a4570c2797a7633e4759c9ba9b258af6.
I'll write a doc on how to use each strategy next week.

**Comment by eMaringolo** [comment]
It is working now.
