### ISSUE TITLE
Support different EOL when exporting to Tonel

### ISSUE THREAD

**Issue by eMaringolo** [vasmalltalk/tonel-vast#3]
The `TonelWriter` has a `lineDelimiter` variable that is not honored when exporting an Application to a Tonel file.

**Comment by eMaringolo** [comment]
@dalehenrich I don't know whether Tonel has any spec regarding the EOL used, or we should proceed supporting a custom EOL.

**Comment by eMaringolo** [comment]
I added the option to customize the EOL, the writer is currently honoring it.

In the latest commit 81af0b1 see `TonelWriter` `useLfEOL`, `useCrEOL` and `useCrLfEOL`.

**Comment by martinmcclure** [comment]
The forthcoming Tonel draft spec specifies that all files should use the native line ending of the local platform (CRLF for Windows, LF for Unix).

**Comment by dalehenrich** [comment]
If I interpret Martins comment correctly, `useCrEOL` should not be a valid option?
