### ISSUE TITLE
./envy/Tonel.dat : Missing required maps

### ISSUE THREAD

**Issue by Noschvie** [vasmalltalk/tonel-vast#33]
The configuration map "Test Tonel" version 1.0 references config map Tonel version 1.48, but latest version is 1.49

```
Test Tonel 1.0
==============
Applications:
	TonelLoaderTests 1.5
	TonelReaderTests 1.30
	TonelWriterTests 1.31
Required Maps:
	Tonel Missing - (26.03.2020 17:52:41)
	z.ST: SUnit V 9.2.1  [457]
```

**Comment by marianopeck** [comment]
Thanks @Noschvie Well spotted. I can confirm it and we will fix it.

**Comment by eMaringolo** [comment]
Please use the [latest release/commit](https://github.com/vasmalltalk/tonel-vast/releases/tag/v1.0.0), we ammended the last one to avoid confusion.

This is fixed now and should work.

**Comment by Noschvie** [comment]
Retested with latest version of `./envy/Tonel.dat` and ok.

```
Test Tonel 1.3
==============
Applications:
	TonelLoaderTests 1.5
	TonelReaderTests 1.30
	TonelWriterTests 1.32
Required Maps:
	Tonel 1.52
	z.ST: SUnit V 9.2.1  [457]
```
