### ISSUE TITLE
#loadWithRequiredMaps should also check  by timestamp

### ISSUE THREAD

**Issue by marianopeck** [vasmalltalk/tonel-vast#48]
Currently, `#loadWithRequiredMaps` is only looking by version name:
        
```smalltalk
 (EmConfigurationMap editionsFor: self name)
		detect: [:one | one versionName = self versionName]
		ifNone: [
```

However, its quite common and likely for versions to be renamed. Therefore, the lookup should be:

Look for versions with exact timestamp...if only one, pick that one, regardless of version name. If more than one, try to detect if there is one with same version name as specified.

**Comment by eMaringolo** [comment]
Fixed by b8339fb
